name: Validate Links

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
